[env:Gateway_TTGO_T3]
platform = espressif32@3.5.0
board = ttgo-lora32-v21
framework = arduino
lib_deps =
  sandeepmistry/LoRa @ ^0.8.0
build_flags =
  -D _WIFIMANAGER=0
  -D _SPIFFS_FORMAT=0
  -D _OLED=1
  -D _DUSB=1
  -D _PROFILER=1
  -D _STRICT_1CH=2
  -D _MAXSEEN=10
  -D _STAT_LOG=0
  -D _LOCALSERVER=2
  -D _BUF_WRITE=0
  -D _EXPERT=1
upload_protocol = esptool
upload_speed = 921600
monitor_speed = 115200
board_build.flash_mode = qio